.TH rotini 1 2014-10-12 Rotini "Rotini"
.SH NAME
rotini - Rotini Windows Decorator
.SH SYNOPSIS
.Brotini [--replace] [--help] [--version]
.SH DESCRIPTION
.I rotini
rotini is the windows decorator for fusilli.
\.
.SH OPTIONS
.TP 5
.RI --replace
Replaces a current running decorator
.TP 5
.RI --version
outputs the current version of
.I rotini
.TP 5
--help
short usage statement about
.I rotini
.SH SIGNALS
.TP 5
.RI USR1
Reloads its settings.
.SH FILES
.TP 5
.RI $HOME/.rotini/settings.ini
Here are the settings stored.
.SH AUTHORS
- Michael Bitches (noodlylight@gmail.com)
- Quinn Storm (livinglatexkali@gmail.com)
.SH "SEE ALSO"
.BR fusilli "(1)
.BR rotini-theme-manager "(1)
