.TH rotini-theme-manager 1 2014-10-12 The Rotini Theme Manager "Rotini Theme Manager"
.SH NAME
rotini-theme-manager - The Rotini Theme Manager
.SH SYNOPSIS
.B rotini-theme-manager 
.SH DESCRIPTION
.I rotini-theme-manager
is the theme manager of rotini.
\.
.TP 5
.RI $HOME/.rotini/settings.ini
Here are the settings stored.
.SH AUTHORS
- Michael Bitches (noodlylight@gmail.com)
- Quinn Storm (livinglatexkali@gmail.com)
.SH "SEE ALSO"
.BR rotini "(1)
